version: '2'

services:

  home-assistant:
    image: homeassistant/home-assistant:latest 
    container_name: home-assistant
    ports: 
      - 8123:8123
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro 
    restart: always
